NeP.GB.objHerb = {
	[181166] = { is = 'Herb', name = 'Bloodthisle' },
	[1618] = { is = 'Herb', name = 'Peacebloom' },
	[1617] = { is = 'Herb', name = 'Silverleaf' },
	[1619] = { is = 'Herb', name = 'Earthroot' },
	[1620] = { is = 'Herb', name = 'Mageroyal' },
	[1621] = { is = 'Herb', name = 'Briarthorn' },
	[2045] = { is = 'Herb', name = 'Stranglekelp' },
	[1622] = { is = 'Herb', name = 'Bruiseweed' },
	[1623] = { is = 'Herb', name = 'Wild Steelbloom' },
	[1628] = { is = 'Herb', name = 'Grave Moss' },
	[1624] = { is = 'Herb', name = 'Kingsblood' },
	[2041] = { is = 'Herb', name = 'Liferoot' },
	[2042] = { is = 'Herb', name = 'Fadeleaf' },
	[2046] = { is = 'Herb', name = 'Goldthorn' },
	[2043] = { is = 'Herb', name = 'Khadgars Whisker' },
	[2044] = { is = 'Herb', name = 'Wintersbite' },
	[2866] = { is = 'Herb', name = 'Firebloom' },
	[142140] = { is = 'Herb', name = 'Purple Lotus' },
	[142142] = { is = 'Herb', name = 'Sungrass' },
	[142143] = { is = 'Herb', name = 'Blindweed' },
	[142144] = { is = 'Herb', name = 'Ghost Mushroom' },
	[142145] = { is = 'Herb', name = 'Gromsblood' },
	[176583] = { is = 'Herb', name = 'Golden Sansam' },
	[176584] = { is = 'Herb', name = 'Dreamfoil' },
	[176586] = { is = 'Herb', name = 'Mountain Silversage' },
	[181270] = { is = 'Herb', name = 'Felweed' },
	[181271] = { is = 'Herb', name = 'Dreaming Glory' },
	[181275] = { is = 'Herb', name = 'Ragveil' },
	[181277] = { is = 'Herb', name = 'Terocone' },
	[189973] = { is = 'Herb', name = 'Goldclover' },
}