NeP.GB.objOre = {
	--[[ //// Classic //// ]]
	[1731] = { is = 'Ore', name = 'Copper Vein' },
	[1732] = { is = 'Ore', name = 'Tin Vein'},
	[1733] = { is = 'Ore', name = 'Silver Vein'},
	[1735] = { is = 'Ore', name = 'Iron Deposit'},
	[1734] = { is = 'Ore', name = 'Gold Vein'},
	[2040] = { is = 'Ore', name = 'Mithril Deposit'},
	[2047] = { is = 'Ore', name = 'Truesilver Deposit'},
	[324] = { is = 'Ore', name = 'Small Thorium Vein'},
	[175404] = { is = 'Ore', name = 'Rich Thorium Vein'},
	[181555] = { is = 'Ore', name = 'Fel Iron Deposit'},
	[181556] = { is = 'Ore', name = 'Adamantite Deposit'},
	[189978] = { is = 'Ore', name = 'Cobalt Deposit'},
	[181569] = { is = 'Ore', name = 'Rich Adamantite Deposit'},
	[181557] = { is = 'Ore', name = 'Khorium Vein'},
	[189979] = { is = 'Ore', name = 'Rich Cobalt Deposit'},
	[189980] = { is = 'Ore', name = 'Saronite Deposit'},
	[189981] = { is = 'Ore', name = 'Rich Saronite Deposit'},
	[191133] = { is = 'Ore', name = 'Titanium Vein'},
	[228510] = { is = 'Ore', name = 'Rich True Iron Deposit' },
	[228493] = { is = 'Ore', name = 'True Iron Deposit' },
	[228564] = { is = 'Ore', name = 'Rich Blackrock Deposit' },
	[228563] = { is = 'Ore', name = 'Blackrock Deposit' },
	[232544] = { is = 'Ore', name = 'True Iron Deposit' },
	[232545] = { is = 'Ore', name = 'Rich True Iron Deposit' },
	[232542] = { is = 'Ore', name = 'Blackrock Deposit' },
	[232543] = { is = 'Ore', name = 'Rich Blackrock Deposit' },
	[232541] = { is = 'Ore', name = 'Mine Cart' },
	[243312] = { is = 'Ore', name = 'Rich Blackrock Deposit' },
	[243313] = { is = 'Ore', name = 'Blackrock Deposit' },
	[243314] = { is = 'Ore', name = 'True Iron Deposit' },
	[243315] = { is = 'Ore', name = 'Rich True Iron Deposit' }
}